### ISSUE TITLE
As a developer, I can upload a .mp3 file for the Web Audio API so that a visual can be created from it

### ISSUE THREAD

**Issue by johnzarnowski** [Clemson-Software-Engineering/Music-Visualizer#13]
- [x] Initialize the Web Audio API in JavaScript (30 minutes). Very simple block of code to setup context, need to make sure the library is included.
- [x] Upload the .mp3 file to the program (one hour). Either use a media context or a simple HML upload file.
- [x] Ensure that the file was uploaded successfully (30 minutes). Show a message to the user that the file was successfully uploaded and make it disappear after a few seconds.

**Comment by johnmhayde** [comment]
Completed via button on html page - shows song title that was uploaded on completion.
