### ISSUE TITLE
As a developer, I can utilize the fast Fourier transform so that I can convert the audio of the music into a visual

### ISSUE THREAD

**Issue by johnzarnowski** [Clemson-Software-Engineering/Music-Visualizer#8]
### Tasks

- [x] Download FFT library and includes in headers. (30 min) @darecluval 
- [ ] Utilize FFT operations to manipulate .wav data to return fat magnitude values (2 hours) @darecluval  

Total Time: 2.5 hours

**Comment by SchmidtWC** [comment]
### Tasks
- Creating the FFT function
- `Performing the FFT function on selected data`
- `Converting the FFT output to a readable output for the visuals`
- Utilizing the .wav or .mp4 as input
- `Dividing the input data into time slices - this is the "selected data"`
